{% set name = "esmtools" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89a875c3deb4d4a8fdec05fd2fbeb79f2b3f7187e0b2117ba7649eb39a05657d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >3.6
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >3.6
    - cftime
    - climpred >=2.1.0
    - numpy
    - scipy
    - statsmodels
    - tqdm
    - xarray >=0.15.1

test:
  imports:
    - esmtools

about:
  home: http://github.com/bradyrx/esmtools
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: a toolbox for Earth System Model analysis
  doc_url: http://esmtools.readthedocs.io/
  dev_url: https://github.com/bradyrx/esmtools

extra:
  recipe-maintainers:
    - bradyrx
